spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:53306/testdb
    username: develop
    password: develop
    #username: admin
    #password: password
  sql:
    init:
      mode: always
