spring:
  datasource:
    url: jdbc:mysql://db-hellospring.cfivmaqlrrxf.ap-northeast-1.rds.amazonaws.com::3306/sampledb?useUnicode=true&serverTimezone=JST
    username: admin
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
