spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-hellospring.cfivmaqlrrxf.ap-northeast-1.rds.amazonaws.com::3306/sampledb?useUnicode=true&serverTimezone=UTC
    #url: jdbc:mysql://db-hellospring.cfivmaqlrrxf.ap-northeast-1.rds.amazonaws.com::3306/sampledb
    #url: jdbc:mysql://localhost:53306/testdb
    #url: jdbc:mysql://localhost:3306/sampledb
    #username: develop
    #password: develop
    username: admin
    password: password
    #username: root
    #password: 108474hi
  sql:
    init:
      mode: always
    