spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-hellospring.cfivmaqlrrxf.ap-northeast-1.rds.amazonaws.com:3306/testdb
    #username: develop
    #password: develop
    username: admin
    password: password
  sql:
    init:
      mode: always
